<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Dan\Source\Repos\PlayerPerformanceAnalyser\Analyser\Analyser\Database.mdf;Integrated Security=True" SettingsObjectName="AnalyserLibrary.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="OpponentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PitchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Game_Lineup" Member="Lineups" ThisKey="GameID" OtherKey="GameID" Type="Lineup" />
      <Association Name="GameType_Game" Member="GameType" ThisKey="GameTypeID" OtherKey="GameTypeID" Type="GameType" IsForeignKey="true" />
      <Association Name="Opponent_Game" Member="Opponent" ThisKey="OpponentID" OtherKey="OpponentID" Type="Opponent" IsForeignKey="true" />
      <Association Name="Pitch_Game" Member="Pitch" ThisKey="PitchID" OtherKey="PitchID" Type="Pitch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimeLine" Member="TimeLines">
    <Type Name="TimeLine">
      <Column Name="TimeLineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReadingTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GPSDeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GPSDevice_TimeLine" Member="GPSDevice" ThisKey="GPSDeviceID" OtherKey="GPSDeviceID" Type="GPSDevice" IsForeignKey="true" />
      <Association Name="Lineup_TimeLine" Member="Lineup" ThisKey="LineupID" OtherKey="LineupID" Type="Lineup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameType" Member="GameTypes">
    <Type Name="GameType">
      <Column Name="GameTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GameType_Game" Member="Games" ThisKey="GameTypeID" OtherKey="GameTypeID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.GPSDevice" Member="GPSDevices">
    <Type Name="GPSDevice">
      <Column Name="GPSDeviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GPSDeviceName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="GPSDevice_TimeLine" Member="TimeLines" ThisKey="GPSDeviceID" OtherKey="GPSDeviceID" Type="TimeLine" />
    </Type>
  </Table>
  <Table Name="dbo.Lineup" Member="Lineups">
    <Type Name="Lineup">
      <Column Name="LineupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lineup_TimeLine" Member="TimeLines" ThisKey="LineupID" OtherKey="LineupID" Type="TimeLine" />
      <Association Name="Game_Lineup" Member="Game" ThisKey="GameID" OtherKey="GameID" Type="Game" IsForeignKey="true" />
      <Association Name="Player_Lineup" Member="Player" ThisKey="PlayerID" OtherKey="PlayerID" Type="Player" IsForeignKey="true" />
      <Association Name="Position_Lineup" Member="Position" ThisKey="PositionID" OtherKey="PositionID" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Opponent" Member="Opponents">
    <Type Name="Opponent">
      <Column Name="OpponentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OpponentName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Opponent_Game" Member="Games" ThisKey="OpponentID" OtherKey="OpponentID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.Pitch" Member="Pitches">
    <Type Name="Pitch">
      <Column Name="PitchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PitchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pitch_Game" Member="Games" ThisKey="PitchID" OtherKey="PitchID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Player_Lineup" Member="Lineups" ThisKey="PlayerID" OtherKey="PlayerID" Type="Lineup" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="PositionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Position" Member="Position1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Position_Lineup" Member="Lineups" ThisKey="PositionID" OtherKey="PositionID" Type="Lineup" />
    </Type>
  </Table>
  <Function Name="dbo.PlayerFullNameProc" Method="PlayerFullNameProc">
    <ElementType Name="PlayerFullNameProcResult">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(71) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PlayerLineupDetailsProc" Method="PlayerLineupDetailsProc">
    <Parameter Name="GameID" Parameter="gameID" Type="System.Int32" DbType="Int" />
    <ElementType Name="PlayerLineupDetailsProcResult">
      <Column Name="LineupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineupDetails" Type="System.String" DbType="VarChar(104) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GameSearchByDateProc" Method="GameSearchByDateProc">
    <Parameter Name="Date" Parameter="date" Type="System.Int32" DbType="Int" />
    <ElementType Name="GameSearchByDateProcResult">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineupDetails" Type="System.String" DbType="VarChar(99) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectOpponentsBarTraining" Method="SelectOpponentsBarTraining">
    <ElementType Name="SelectOpponentsBarTrainingResult">
      <Column Name="OpponentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpponentName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GameDetailsProc" Method="GameDetailsProc">
    <ElementType Name="GameDetailsProcResult">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameDetails" Type="System.String" DbType="VarChar(109) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GameSearchByOpponentProc" Method="GameSearchByOpponentProc">
    <Parameter Name="Opponent" Parameter="opponent" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="GameSearchByOpponentProcResult">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineupDetails" Type="System.String" DbType="VarChar(99) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GameDetailsByOppProc" Method="GameDetailsByOppProc">
    <Parameter Name="opponent" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="GameDetailsByOppProcResult">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameDetails" Type="System.String" DbType="VarChar(109) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>